# Generated by Django 4.1.1 on 2022-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contac_address_customer_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='xyz@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
