# Generated by Django 4.1.1 on 2022-11-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customer_contact_address_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
