# Generated by Django 4.1.1 on 2022-11-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_housesold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesold',
            name='id',
        ),
        migrations.AlterField(
            model_name='housesold',
            name='house_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
