# Generated by Django 4.1.3 on 2022-11-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customercontacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontacted',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
